version: '3'
services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: infinitum/laravel-docker
    container_name: laravel-docker-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app/:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-docker-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-docker-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "4430:443"
    volumes:
      - ./app/:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-docker-network

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: laravel-docker-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravel-docker-volumes-mysql:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-docker-network

  # MySQL Service
  postgresql:
    image: postgres:11
    container_name: laravel-docker-postgresql
    restart: unless-stopped
    tty: true
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      DB_USER: laravel
      DB_PASSWORD: secret
      DB_NAME: laravel , test2
    volumes:
      - laravel-docker-volumes-postgresql:/var/lib/postgresql/data/
      - ./docker/postgresql/initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - laravel-docker-network

#Docker Networks
networks:
  laravel-docker-network:
    driver: bridge

#Volumes
volumes:
  laravel-docker-volumes-mysql:
    driver: local
  laravel-docker-volumes-postgresql:
    driver: local
