version: '3'
services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/7.3/Dockerfile
    image: infinitum/php
    container_name: infinitum-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app/:/var/www
      - ./docker/php/7.3/local.ini:/usr/local/etc/php/conf.d/local.ini
#      - ./docker/php/7.3/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - infinitum-volumes-phpsocket:/run/php
    networks:
      - infinitum-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: infinitum-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "4430:443"
    volumes:
      - ./app/:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - infinitum-volumes-phpsocket:/run/php
    networks:
      - infinitum-network

  # Redis store
  redis:
    image: redis:alpine
    container_name: infinitum-redis
    restart: unless-stopped
    tty: true
    ports:
      - "63790:6379"
    volumes:
      - infinitum-volumes-redis:/data/
#      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - infinitum-network

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: infinitum-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: infinitum
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - infinitum-volumes-mysql:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - infinitum-network

  # PostgreSQL Service
  postgresql:
    image: postgres:11
    container_name: infinitum-postgresql
    restart: unless-stopped
    tty: true
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      DB_USER: infinitum
      DB_PASSWORD: secret
      DB_NAME: infinitum , test2
    volumes:
      - infinitum-volumes-postgresql:/var/lib/postgresql/data/
      - ./docker/postgresql/initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - infinitum-network

#Docker Networks
networks:
  infinitum-network:
    driver: bridge

#Volumes
volumes:
  infinitum-volumes-mysql:
    driver: local
  infinitum-volumes-postgresql:
    driver: local
  infinitum-volumes-redis:
    driver: local
  infinitum-volumes-phpsocket:
    driver: local
